




# Mac: no path to exec: https://stackoverflow.com/questions/8146249/jekyll-command-not-found
# gem install -n ~/bin jekyll

run-dev-p4000:
	bundle exec jekyll serve --livereload --trace
run-prod-p4000:
	bundle exec jekyll serve --port 8080

install:
	gem install jekyll bundler

install-mac:
	gem install -n ~/bin jekyll
	~/bin/jekyll new fulmine


